Create landing: AboutUs & Advertisement components
CA-G12/BMS pull request #69
Opened 2022-10-17 08:02 UTC by bayan2002

2022-10-17 09:58 UTC, tareq-abuaqlain submitted a review, later dismissed

2022-10-17 13:38 UTC, Mai-Elhajeen submitted a review, later dismissed

2022-10-17 13:39 UTC, tareq-abuaqlain submitted a review, later dismissed

2022-10-18 00:25 UTC, Mu7ammadAbed requested changes

2022-10-18 00:25 UTC, Mu7ammadAbed commented on client/src/components/landing/AdvertisementsContainer.tsx
> +            <AdvertisementCard info={ad} />
add key here

2022-10-18 00:25 UTC, Mu7ammadAbed commented on client/src/components/landing/AdvertisementCard.tsx
> +        </Button>,
Do we really need this button?
I mean, Is there a private page for the specific ad ? or are all the data represented here in the card?

2022-10-18 00:25 UTC, Mu7ammadAbed commented on client/src/components/landing/AdvertisementCard.tsx
> +//   return (
remove these

2022-10-18 07:47 UTC, tareq-abuaqlain approved these changes

2022-10-18 07:48 UTC, Mu7ammadAbed approved these changes

2022-10-18 07:48 UTC, Mai-Elhajeen approved these changes

2022-10-18 07:50 UTC, mohjaps approved these changes

2022-10-18 07:50 UTC, merged